### ISSUE TITLE
Swipe in React: Mysterious swipe-item cloning if continuous=true

### ISSUE THREAD

**Issue by DerTomm** [lyfeyaj/swipe#96] opened 2018-01-13 21:19 UTC
Hi,

today I used Swipe for the first time - thanks for keeping swipe alive.
This problem I just realized:

Situation: Two *SwipeItem* are put into the parent *Swipe* component:
```/******************************************************************************************************************************** */
  render() {
    return (
      <Swipe
        className='swipeContainer'
        startSlide={0}
        speed={300}
        auto={0}
        draggable={false}
        continuous={false}
        autoRestart={true}
        disableScroll={false}
        stopPropagation={false} >

        <SwipeItem>
          <div className="exampleOne">...</div>
          <div className="exampleTwo">...</div>
          <div className="exampleThree">...</div>
        </SwipeItem>
        <SwipeItem>
          <div className="exampleOne">...</div>
          <div className="exampleTwo">...</div>
          <div className="exampleThree">...</div>
        </SwipeItem>
      </Swipe>
    );
  }
```

If I set continuous to *false* the DOM looks this way:
![grafik](https://user-images.githubusercontent.com/7753313/34910124-ff74b23e-f8ae-11e7-920f-3f011b3bae36.png)

However, setting continuous to *true* leads to this DOM:
![grafik](https://user-images.githubusercontent.com/7753313/34910130-2199d5d8-f8af-11e7-96ee-551f415b3184.png)

That causes that you do not see just the two slides but also two empty ones before you return to the first one. Do you have any idea why the two swipe-items are cloned?

**Comment by lyfeyaj** [comment] 2018-01-15 06:16
Seems a bug, will check later

**Comment by hogaFarming** [comment] 2018-03-05 16:30
@lyfeyaj  I think this is not a bug.
They are helper elements to make the *continuous* work because you only have 2 *SwipItem*(leq 2 items).
In fact, it should have at least 3 elements in DOM to make the *infinite feel* possible. @

**Comment by hogaFarming** [comment] 2018-03-05 16:34
Can just close this issues.

**Comment by arkonan** [comment] 2018-03-05 17:32
I am also seeing this problem.  

I would expect the plugin to need to create clones of the existing items to implement the continuous swiping.  What makes this seem like a bug rather than intended behavior is that the extra items are empty.

**Comment by dcflow** [comment] 2018-07-11 16:43
@hogaFarming you're right ... but it should also work with 2 elms .. comment out these lines for a quick fix
```
if (children.length === 2) {
     children.push(this.cloneSwipeItem(children[0]));
    children.push(this.cloneSwipeItem(children[1]));
}
```

**Comment by tbaustin** [comment] 2018-07-19 14:21
Since this only happens with two children, you can just do a static check with the callback. Check the index to see if it has gone into the duplicates and change the slide accordingly. It won't look as clean though, and I'm assuming that is why they cloned them, but you don't want your audience to look at nothing for two slides so this is a fix I have done.

`callback: this.onSlideChange.bind(this)` inside of `swipeOptions`

```
onSlideChange(n, elem) {
		// Scroll thumbnails
		const { ul } = this
		const slides = ul.querySelectorAll(`.thumbnail`)
		slides.forEach(s => {
			s.classList.remove(`active`)
		})
		const slide = ul.querySelector(`.tn${n}`)
		if (slide) {
			slide.classList.add(`active`)
			ul.scrollLeft = slide.offsetLeft - ul.clientWidth / 2 + 60
		} else {
			// fix bug in react-swipe with 2 images
			if (this.props.images.length === 2) {
				if (n === 2) {
					this.reactSwipe.slide(0, 300)
					const firstSlide = ul.querySelector(`.tn0`)
					firstSlide.classList.add(`active`)
				}
				if (n === 3) {
					this.reactSwipe.slide(1, 300)
					const secondSlide = ul.querySelector(`.tn1`)
					secondSlide.classList.add(`active`)
				}
			} else {
				// for any other case (that is a bug) just reset to first index
				this.reactSwipe.slide(0, 300)
				const firstSlide = ul.querySelector(`.tn0`)
				firstSlide.classList.add(`active`)
			}
		}
	}
```

**Closed** 2020-02-15 04:19 UTC
Labels: bug
