### ISSUE TITLE
main.js:51062 Uncaught TypeError: Cannot set property 'Swipe' of undefined

### ISSUE THREAD

**Issue by laengyog** [lyfeyaj/swipe#67] opened 2017-04-20 03:06 UTC
in react : 
![image](https://cloud.githubusercontent.com/assets/7719602/25211737/514a6b36-25b9-11e7-9c8e-27d926c6d5ce.png)

**Comment by liyatang** [comment] 2017-04-26 10:24
+1 ， webpack translate this to undefined(line 29)

**Comment by lyfeyaj** [comment] 2017-04-27 02:55
@laengyog @liyatang which version of webpack do you use?

**Comment by owcc** [comment] 2017-05-16 02:23
same error with react! v2.2.6

**Comment by owcc** [comment] 2017-05-16 04:02
same problem! webpack@1.13.1

**Comment by dashkevych** [comment] 2019-12-04 17:51
I am getting the same issue when using **babel** with '@babel/preset-env' in gulp.

`
Uncaught TypeError: Cannot set property 'Swipe' of undefined
    at swipe.js:50
    at swipe.js:52
`

![JS issue](https://snipboard.io/qJrEZ6.jpg)

**Comment by postbird** [comment] 2020-05-07 13:59
same issue with weback@4.42.0

**Comment by postbird** [comment] 2020-05-09 09:36
Duplicate of #135

**Comment by lyfeyaj** [comment] 2020-05-12 18:24
Fixed in #136

**Closed by lyfeyaj** 2020-05-12 18:24 UTC
