### ISSUE TITLE
No pagination

### ISSUE THREAD

**Issue by Mis-tian** [lyfeyaj/swipe#78] opened 2017-06-27 15:39 UTC
No pagination?Is extended by yourself?

**Comment by loup-brun** [comment] 2017-06-27 16:30
Hi,

I am working on a collection of UI components built specifically for the Swipe library. A pagination component will be part of the collection 😉.

If you want to have slide pagination, yes, implementation is left to the developer, but it's fairly simple to achieve.

If you want a slide counter, you can declare a function that updates on slide change (that runs through the `callback`).

For example:

```js
function updatePagination(currentSlide) {
  // assuming paginationElem is the DOM element you want to update
  paginationElem.innerHTML = currentSlide;
}
```

You can have access to the current slide through the Swipe [API](https://github.com/lyfeyaj/swipe#api) and through the `callback` function (see [Config](https://github.com/lyfeyaj/swipe#config-options)).

```js
window.mySwipe = new Swipe(elem, {
  // options...
  callback: function(index) {
    updatePagination(index); // update pagination on slide change
  }
});

// Update pagination through the Swipe API
updatePagination(mySwipe.getPos());

// You can also use the Swipe API to dynamically set the total number of slides
// by using the `getNumSlides` method.
totalElem.innerHTML = mySwipe.getNumSlides();
```

Happy hacking! I'll close this issue one for now (since it's not a bug), but feel free to comment on if you have further questions! 😄

**Closed by loup-brun** 2017-06-27 16:30 UTC
