### ISSUE TITLE
problem when many childs

### ISSUE THREAD

**Issue by iulo** [lyfeyaj/swipe#14] opened 2015-11-18 05:11 UTC
like:

    <div id="slider" class="swipe">
      <div class="swipe-wrap">
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        ...
        <div></div>
      </div>
    </div>

the browser crashes especially in iOS.
I guess is that the memory overflowed.
Do you have any ways to deal with the problem ?

**Comment by loup-brun** [comment] 2015-11-21 23:49
Hi @iulo,

Your markup appears to be pretty standard. Could you please provide more details regarding your implementation? Are you _sure_ that `Swipe` causing these crashes (please try to load the page repeatedly **without** initializing `Swipe` and compare the results)?

Here are some ideas to look at:

* How many slides do you have on your page?
* Do you have multiple carousels on the same page working simultaneously?
* Could another script be causing the error or conflict with `Swipe`?

I doubt crashing is caused by the `Swipe` library itself - I use it in multiple instances and it works fine, even with 20+ slides.

I'll close this for now, please re-open if the problem persists (and that there is clear evidence that `Swipe` is responsible for the problem). There is not enough information to solve your issue here.

**Closed by loup-brun** 2015-11-21 23:49 UTC

**Comment by iulo** [comment] 2015-11-24 03:03
please try 50+ in ios
